# Generated by Django 4.2.4 on 2023-09-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xPosition', models.IntegerField()),
                ('yPosition', models.IntegerField()),
                ('image', models.ImageField(upload_to='product_images')),
            ],
        ),
    ]
